version: '3.3'

volumes:
  marcus_db-data:
    external: true
  # s3-data:

services:
  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - marcus_db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    ports:
      - 4449:5432

  typebot-builder:
    image: typebot-builder:latest
    build:
      context: .
      args:
        - SCOPE=builder
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  typebot-viewer:
    image: typebot-viewer:latest
    build:
      context: .
      args:
        - SCOPE=viewer
    restart: always
    ports:
      - '8081:3000'
    env_file: .env

  # minio:
  #   image: minio/minio
  #   command: server /data
  #   ports:
  #     - '9000:9000'
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #   volumes:
  #     - s3-data:/data
  # # This service just makes sure a bucket with the right policies is created
  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     sleep 10;
  #     /usr/bin/mc config host add minio http://minio:9000 minio minio123;
  #     /usr/bin/mc mb minio/typebot;
  #     /usr/bin/mc anonymous set public minio/typebot/public;
  #     exit 0;
  #     "
